# Generated by Django 3.1.4 on 2020-12-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20201229_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonentity',
            name='defense',
            field=models.IntegerField(default=20, max_length=3),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='health',
            field=models.IntegerField(default=100, max_length=3),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='level',
            field=models.IntegerField(default=1, max_length=3),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='stamina',
            field=models.IntegerField(default=20, max_length=3),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='strength',
            field=models.IntegerField(default=20, max_length=3),
        ),
    ]
