# Generated by Django 3.1.4 on 2020-12-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_auto_20201231_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='previous_evolution',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ManyToManyField(blank=True, null=True, related_name='_pokemon_previous_evolution_+', to='pokemon_entities.Pokemon', verbose_name='Из кого эволюционирует'),
        ),
    ]
